<?php

// Account modal forms
use Drupal\financials_ctools\ModalForms\AccountAdd;
use Drupal\financials_ctools\ModalForms\AccountEdit;

// Transaction modal forms
use Drupal\financials_ctools\ModalForms\TransactionAdd;
use Drupal\financials_ctools\ModalForms\TransactionEdit;

// Transfers
use Drupal\financials_ctools\ModalForms\TransferAdd;
use Drupal\financials_ctools\ModalForms\TransferEdit;

/**
 * Implements hook_ctools_plugin_directory().
 */
function financials_ctools_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
  return null;
}

/**
 * Implements hook_menu().
 */
function financials_ctools_menu() {
  $items['accounts/%ctools_js/add'] = array(
    'title' => 'Add account',
    'page callback' => 'financials_ctools_account_modal_form',
    'page arguments' => array(2, null),
    'access arguments' => array('create finance_account content'),
  );
  $items['accounts/%ctools_js/edit/%node'] = array(
    'title' => 'Add account',
    'page callback' => 'financials_ctools_account_modal_form',
    'page arguments' => array(2, 4),
    'access arguments' => array('edit own finance_account content'),
  );
  $items['transactions/%ctools_js/add'] = array(
    'title' => 'Add transaction',
    'page callback' => 'financials_ctools_transaction_modal_form',
    'page arguments' => array(2, null),
    'access arguments' => array('financials add line item'),
  );
  $items['transactions/%ctools_js/edit/%commerce_line_item'] = array(
    'title' => 'Add transaction',
    'page callback' => 'financials_ctools_transaction_modal_form',
    'page arguments' => array(1, 3),
    'access arguments' => array('financials add line item'),
  );
  $items['transfers/%ctools_js/add'] = array(
    'title' => 'Add transfer',
    'page callback' => 'financials_ctools_transfer_modal_form',
    'page arguments' => array(2, null),
    'access arguments' => array('financials add line item'),
  );
  $items['budget/%ctools_js/add'] = array(
    'title' => 'Add budget item',
    'page callback' => 'financials_ctools_budget_modal_form',
    'page arguments' => array(2, null),
    'access arguments' => array('financials add line item'),
  );
  $items['budget/%ctools_js/edit/%commerce_line_item'] = array(
    'title' => 'Edit budget item',
    'page callback' => 'financials_ctools_budget_modal_form',
    'page arguments' => array(1, 3),
    'access arguments' => array('financials add line item'),
  );
  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function financials_ctools_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path == 'accounts') {
    ctools_include('modal');
    ctools_modal_add_js();

    // Reset local tasks for ctools modal friendly links.
    $data['actions']['output'] = array();

    $item = menu_get_item('accounts/nojs/add');
    if ($item['access']) {
      $item['title'] = t('Add account');
      $item['localized_options']['attributes']['class'][] = 'ctools-use-modal';
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
    $item = menu_get_item('transactions/nojs/add');
    if ($item['access']) {
      $item['localized_options']['attributes']['class'][] = 'ctools-use-modal';
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
    $item = menu_get_item('transfers/nojs/add');
    if ($item['access']) {
      $item['localized_options']['attributes']['class'][] = 'ctools-use-modal';
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
  if ($root_path == 'budget') {
    ctools_include('modal');
    ctools_modal_add_js();

    $item = menu_get_item('accounts/nojs/add');
    if ($item['access']) {
      $item['title'] = t('Add account');
      $item['localized_options']['attributes']['class'][] = 'ctools-use-modal';
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
    $item = menu_get_item('budget/nojs/add');
    if ($item['access']) {
      $item['localized_options']['attributes']['class'][] = 'ctools-use-modal';
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_financials_account_transactions_rows_alter().
 */
function financials_ctools_financials_account_transactions_rows_alter(&$rows, $accountID) {
  ctools_include('modal');
  ctools_modal_add_js();
  foreach ($rows as $key => $table_row) {
    $rows[$key][3]['data']['#path'] = 'transactions/nojs/edit/' . $rows[$key][3]['data']['#transaction_id'];
    $rows[$key][3]['data']['#options']['attributes']['class'][] = 'ctools-use-modal';
  }
}

/**
 * Implements hook_financials_budget_item_rows_alter().
 */
function financials_ctools_financials_budget_item_rows_alter(&$rows) {
  ctools_include('modal');
  ctools_modal_add_js();
  foreach ($rows as $key => $table_row) {
    if (!isset($rows[$key]['data'][4])) {
      continue;
    }
    $rows[$key]['data'][4]['data']['#path'] = 'budget/nojs/edit/' . $rows[$key]['data'][4]['data']['#budget_item_id'];
    $rows[$key]['data'][4]['data']['#options']['attributes']['class'][] = 'ctools-use-modal';
  }
}

/**
 * Node add modal for accounts.
 *
 * @param bool $js
 * @param \stdClass $node
 *
 * @return array|mixed
 */
function financials_ctools_account_modal_form($js = false, $node = null) {
  if ($node == NULL) {
    $modalHandler = new AccountAdd('finance_account_node_form',
      array(\Drupal\financials\Entity\AccountNode::newStub()), $js);
  }
  else {
    $modalHandler = new AccountEdit('finance_account_node_form', array($node),
      $js);
  }
  $modalHandler->output();
}

/**
 * @param bool $js
 * @param null $line_item
 */
function financials_ctools_transaction_modal_form($js = false, $line_item = null) {
  if ($line_item == null) {
    $line_item = \Drupal\financials\Entity\TransactionLineItem::newStub();
    $modalHandler = new TransactionAdd('financials_add_transaction_form', array($line_item), $js);
  }
  else {
    $modalHandler = new TransactionEdit('financials_add_transaction_form', array($line_item), $js);
  }
  $modalHandler->output();
}

/**
 * @param bool $js
 * @param null $line_item
 */
function financials_ctools_transfer_modal_form($js = false, $line_item = null) {
  if ($line_item == null) {
    $line_item = \Drupal\financials\Entity\TransactionLineItem::newStub();
    $modalHandler = new TransferAdd('financials_transfer_transaction_form', array($line_item), $js);
  }
  else {
    $modalHandler = new TransferEdit('financials_transfer_transaction_form', array($line_item), $js);
  }
  $modalHandler->output();
}

/**
 * @param bool $js
 * @param null $line_item
 */
function financials_ctools_budget_modal_form($js = false, $line_item = null) {
  if ($line_item == null) {
    $line_item = \Drupal\financials\Entity\BudgetLineItem::newStub();
    $modalHandler = new TransferAdd('financials_add_budget_form', array($line_item), $js);
  }
  else {
    $modalHandler = new TransferEdit('financials_add_budget_form', array($line_item), $js);
  }
  $modalHandler->output();
}